# -*- coding: utf-8 -*-
"""capstone.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YGPxL5UeyYOs6n5v73b0BbJC8-BMEy4C
"""

import streamlit as st
import pandas as pd
import requests
import plotly.express as px

def fetch_covid_data():
    url = "https://covid.ourworldindata.org/data/owid-covid-data.csv"
    try:
        df = pd.read_csv(url)
        return df
    except Exception as e:
        st.error(f"Error fetching data: {e}")
        return None

# Load Data
st.title("COVID-19 Daily Tracker")
st.sidebar.header("Select Options")

data = fetch_covid_data()
if data is not None:
    countries = data['location'].unique()
    selected_countries = st.sidebar.multiselect("Select Countries", countries, default=["United States"])
    data_type = st.sidebar.radio("Select Data Type", ["Daily Cases", "Cumulative Cases"])

    # Process Data
    data_filtered = data[data['location'].isin(selected_countries)]
    data_filtered = data_filtered[['location', 'date', 'new_cases', 'total_cases']]

    if data_type == "Daily Cases":
        fig = px.line(data_filtered, x='date', y='new_cases', color='location', title="Daily COVID-19 Cases")
    else:
        fig = px.line(data_filtered, x='date', y='total_cases', color='location', title="Cumulative COVID-19 Cases")

    st.plotly_chart(fig)